<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE empresa [
    <!ELEMENT empresa (empleado)*>
    <!ELEMENT empleado (nombre, apellido+, telefono, email, direccion)>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT apellido (#PCDATA)>
    <!ELEMENT telefono (#PCDATA)>
    <!ELEMENT email (#PCDATA)>
    <!ELEMENT direccion (ciudad, provincia, cp)>
    <!ELEMENT ciudad (#PCDATA)>
    <!ELEMENT provincia (#PCDATA)>
    <!ELEMENT cp (#PCDATA)>
]>
<empresa>
    <empleado>
        <nombre>Alejandro</nombre>
        <apellido>Ortiz</apellido>
        <telefono>653392017</telefono>
        <email>jandruco7@gmail.com</email>
        <direccion>
            <ciudad>Santander</ciudad>
            <provincia>Cantabria</provincia>
            <cp>39009</cp>
        </direccion>
    </empleado>
    <empleado>
        <nombre>Roberto</nombre>
        <apellido>VÃ¡zquez</apellido>
        <telefono>685423695</telefono>
        <email>pepeowen@hotmail.com</email>
        <direccion>
            <ciudad>Santander</ciudad>
            <provincia>Cantabria</provincia>
            <cp>39011</cp>
        </direccion>
    </empleado>
</empresa>