<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE equipos [
    <!ELEMENT equipos (equipo+)>
    <!ELEMENT equipo (nombre, ciudad, entrenador, plantilla)>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT ciudad (#PCDATA)>
    <!ELEMENT entrenador EMPTY>
    <!ELEMENT plantilla (jugador+)>
    <!ELEMENT jugador (nombrej, nacionalidad)>
        <!ATTLIST jugador posicion (Portero|Defensa|Medio|Delantero) #REQUIRED>
    <!ELEMENT nombrej (#PCDATA)>
    <!ELEMENT nacionalidad (#PCDATA)>
]>
<equipos>
    <equipo>
        <nombre>Real Racing Club</nombre>
        <ciudad>Santander</ciudad>
        <entrenador/>
        <plantilla>
            <jugador posicion="Portero">
                <nombrej>Luca Zidane</nombrej>
                <nacionalidad>Francés</nacionalidad>
            </jugador>
            <jugador posicion="Delantero">
                <nombrej>Karim Yoda</nombrej>
                <nacionalidad>Francés</nacionalidad>
            </jugador>
        </plantilla>          
    </equipo>
    <equipo>
        <nombre>Real Madrid</nombre>
        <ciudad>Madrid</ciudad>
        <entrenador/>
        <plantilla>
            <jugador posicion="Defensa">
                <nombrej>Eder Militao</nombrej>
                <nacionalidad>Brasileño</nacionalidad>
            </jugador>
            <jugador posicion="Delantero">
                <nombrej>Eden Hazard</nombrej>
                <nacionalidad>Belga</nacionalidad>
            </jugador>
        </plantilla>
    </equipo>
</equipos>