=== jandruco/moduloxml/inventario2/inventario2.dtd
<!ELEMENT inventario (objeto+)>
<!ELEMENT objeto (mesa|ordenador)>
  <!ATTLIST objeto codigo CDATA #IMPLIED>
  <!ELEMENT mesa (tipo?,localizacion)>
    <!ELEMENT tipo (#PCDATA)>
    <!ELEMENT localizacion (#PCDATA)>
  <!ELEMENT ordenador (procesador?, memoria?, discoduro?)>
    <!ELEMENT procesador (#PCDATA)>
    <!ATTLIST procesador fabricante CDATA #IMPLIED>
    <!ELEMENT memoria (#PCDATA)>
    <!ATTLIST memoria unidad CDATA #REQUIRED>
    <!ELEMENT discoduro (#PCDATA)>

=== jandruco/moduloxml/inventario2/inventario2.xml
<?xml version = "1.0" encoding = "UTF-8"?>
<!DOCTYPE inventario SYSTEM "inventario2.dtd">
<inventario>
    <objeto codigo="MM28089">
      <mesa>
        <tipo>Oficina</tipo>
        <localizacion>B09</localizacion>
      </mesa>
    </objeto>
    <objeto>
      <ordenador>
        <procesador fabricante="Intel">i3</procesador>
        <memoria unidad="GB">2</memoria>
        <discoduro>520</discoduro>
      </ordenador>
    </objeto>
</inventario>
